### PR TITLE
String comparison

### PR DESCRIPTION
**Pull request by omersek**
- Added <=> method to String class
- Fixed Array sort method (block)

`.sort { |a,b| a <=> b }`
now works :)

### CODE REVIEW

**Comment by sbagdat** [comment]
Thanks! 💎

**Comment by omersek** [comment]
You're welcome, and I thank you, I learned lots of new things about ruby :)

**Comment by omersek** [comment]
Hi, I checked the new release, realized that you removed my Array#sort changes, may I ask why? if you tell me what was wrong, I can improve it today

```
ary = ["İsmet", "Zeliha", "Şakir"]
puts ary.sort { |a,b| a <=> b }
```

this works, but

```
ary = [["İsmet", 0], ["Zeliha", 1], ["Şakir", 2]]
puts ary.sort { |a,b| a[0] <=> b[0] }
```

gives error:

`undefined method 'chars' for ["İsmet", 0]:Array`

**Comment by sbagdat** [comment]
Hi @omersek,
Your code "calling super() if block_given?" was broking everything when using sort method with a block, because it was passing control to original sort method. This is why I removed your changes.

You can anytime send a new pull request. BTW please include or modify tests for your newly added code.

**Comment by omersek** [comment]
@sbagdat yeah, actually my goal was exactly that, because current Array#sort method can't handle every cases when you use it with a block. I need to know what is broken to make a new PR, what do you mean by "was broking everything" ? btw I have no idea about using tests in ruby, i do my test manually :( next time i'll give it a try

**Comment by sbagdat** [comment]
You can use `ary.public_send(:sort) { |a,b| a[0] <=> b[0] }` for now and get the benefit of what is gem offering. Whenever I have some freetime, I'll look at it to make the gem has it by default. Have a nice day 👍

**Comment by sbagdat** [comment]
You can now use v1.1.1, hope it helps :)

**Comment by sbagdat** [comment]
@omersek Looks like you were right from the beginning. While I was updating tests for Array#sort, I realized my mistake. I hope, all is well right now. Thank you for your effort to fix this 🥇

**Pull request merged**
